// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddCapital(arg1:number,arg2:string):Promise<main.Response>;

export function AddMotor(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:string,arg7:string,arg8:string,arg9:string,arg10:string,arg11:string,arg12:string):Promise<main.Response>;

export function CheckNomorPolisiExists(arg1:string,arg2:string):Promise<main.Response>;

export function CheckPermission(arg1:string,arg2:string):Promise<boolean>;

export function CleanupExpiredSessions():Promise<void>;

export function CleanupMotorDocuments(arg1:string):Promise<void>;

export function CreateSession(arg1:string):Promise<string>;

export function CreateSessionsTable():Promise<void>;

export function CreateTransaction(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:string):Promise<main.Response>;

export function CreateUsersTable():Promise<void>;

export function DeleteMotor(arg1:string):Promise<main.Response>;

export function DeleteMotorDocument(arg1:string):Promise<main.Response>;

export function EnsureDocumentsFolder():Promise<void>;

export function EnsureMotorFolder(arg1:string):Promise<void>;

export function GetAvailableMotorsForSale():Promise<main.Response>;

export function GetAvailableYears():Promise<main.Response>;

export function GetCapitalTransactions():Promise<main.Response>;

export function GetCurrentCapital():Promise<main.Response>;

export function GetCurrentUser(arg1:string):Promise<main.Response>;

export function GetDocumentsBasePath():Promise<string>;

export function GetFinancialSummary():Promise<main.Response>;

export function GetFinancialSummaryByYear(arg1:string):Promise<main.Response>;

export function GetMotorByID(arg1:string):Promise<main.Response>;

export function GetMotorDocumentFile(arg1:string):Promise<main.Response>;

export function GetMotorDocuments(arg1:string):Promise<main.Response>;

export function GetMotorDocumentsPath(arg1:string):Promise<string>;

export function GetMotors():Promise<main.Response>;

export function GetMotorsByStatus(arg1:string):Promise<main.Response>;

export function GetPendapatanBulanan(arg1:string):Promise<main.Response>;

export function GetTodayPurchasedMotors():Promise<main.Response>;

export function GetTodaySoldMotors():Promise<main.Response>;

export function GetTodayStats():Promise<main.Response>;

export function GetTransactions():Promise<main.Response>;

export function GetUserByID(arg1:string):Promise<main.User>;

export function GetUserByUsername(arg1:string):Promise<main.User>;

export function InvalidateSession(arg1:string):Promise<void>;

export function Login(arg1:string,arg2:string):Promise<main.Response>;

export function Logout(arg1:string):Promise<main.Response>;

export function RequirePermission(arg1:string,arg2:string):Promise<void>;

export function SearchMotors(arg1:string):Promise<main.Response>;

export function SearchTransactions(arg1:string,arg2:string,arg3:string):Promise<main.Response>;

export function SeedUsers():Promise<void>;

export function SubtractCapital(arg1:number,arg2:string):Promise<main.Response>;

export function UpdateLastLogin(arg1:string):Promise<void>;

export function UpdateMotor(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number,arg7:string,arg8:string,arg9:string,arg10:string,arg11:string,arg12:string,arg13:string,arg14:string):Promise<main.Response>;

export function UpdateMotorStatus(arg1:string,arg2:string):Promise<main.Response>;

export function UploadMotorDocument(arg1:string,arg2:string,arg3:string,arg4:string):Promise<main.Response>;

export function ValidateSession(arg1:string):Promise<main.User>;
