// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddMotor(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:string,arg7:string,arg8:string):Promise<main.Response>;

export function CheckNomorPolisiExists(arg1:string,arg2:string):Promise<main.Response>;

export function DeleteMotor(arg1:string):Promise<main.Response>;

export function GetFinancialSummary():Promise<main.Response>;

export function GetMotorByID(arg1:string):Promise<main.Response>;

export function GetMotors():Promise<main.Response>;

export function GetMotorsByStatus(arg1:string):Promise<main.Response>;

export function GetPendapatanBulanan():Promise<main.Response>;

export function SearchMotors(arg1:string):Promise<main.Response>;

export function UpdateMotor(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:number,arg7:string,arg8:string,arg9:string):Promise<main.Response>;

export function UpdateMotorStatus(arg1:string,arg2:string):Promise<main.Response>;
