// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMotor(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AddMotor'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteMotor(arg1) {
  return window['go']['main']['App']['DeleteMotor'](arg1);
}

export function GetFinancialSummary() {
  return window['go']['main']['App']['GetFinancialSummary']();
}

export function GetMotorByID(arg1) {
  return window['go']['main']['App']['GetMotorByID'](arg1);
}

export function GetMotors() {
  return window['go']['main']['App']['GetMotors']();
}

export function GetMotorsByStatus(arg1) {
  return window['go']['main']['App']['GetMotorsByStatus'](arg1);
}

export function GetPendapatanBulanan() {
  return window['go']['main']['App']['GetPendapatanBulanan']();
}

export function SearchMotors(arg1) {
  return window['go']['main']['App']['SearchMotors'](arg1);
}

export function UpdateMotor(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['UpdateMotor'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateMotorStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateMotorStatus'](arg1, arg2);
}
